media: assets/img
content:
  - name: tools
    label: Tools
    type: collection
    path: '_tools'
    view:
      fields: [ title, tags ]
    fields:
      - name: layout
        label: Layout
        type: select
        required: true
        options:
          values: [ tool, stack ]
      - name: tags
        label: Tags
        type: select
        options:
          values: [ design, development, productivity, media ]
      - name: title
        label: Title
        type: string
        required: true
      - name: summary
        label: Summary
        type: string
        required: true
      - name: link
        label: Link
        type: string
        required: true
      - name: image-html
        label: Image HTML
        type: code
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: bookmarks
    label: Bookmarks
    type: collection
    path: '_bookmarks'
    view:
      fields: [ title, tags ]
    fields:
      - name: layout
        label: Layout
        type: select
        required: true
        options:
          values: [ tool, stack ]
      - name: tags
        label: Tags
        type: select
        options:
          values: [ design, development, productivity, media ]
      - name: title
        label: Title
        type: string
        required: true
      - name: summary
        label: Summary
        type: string
        required: true
      - name: link
        label: Link
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
  - name: inspiration
    label: Inspiration
    type: collection
    path: '_inspiration'
    view:
      fields: [ title, tags ]
    fields:
      - name: layout
        label: Layout
        type: select
        required: true
        options:
          values: [ tool, stack ]
      - name: tags
        label: Tags
        type: select
        options:
          values: [ design, development, productivity, media ]
      - name: title
        label: Title
        type: string
        required: true
      - name: link
        label: Link
        type: string
        required: true
      - name: image
        label: Image
        type: image
        required: true
      - name: body
        label: Body
        type: rich-text